const { Router } = require("express");
const resourceMap = require("./resourceMap.json");
const authRoutes = require("./authRoutes");
const paymentRoutes = require("./payment");
const couponRoutes = require("./couponRoutes");
const checkoutOrderRoutes = require("./Checkoutorderroutes");
const coursejobRoutes = require("./coursejobRoutes");
const lessonNoteRoutes = require("./lessonNoteRoutes");
const batchRoutes = require("./batchRoutes"); // ADD THIS

const router = Router();

router.get("/health", (req, res) => res.json({ success: true, message: "API is healthy" }));

router.use("/auth", authRoutes);
router.use("/users", require("./userRoutes")); 
router.use("/audit-logs", require("./auditLogRoutes"));
router.use("/payment", paymentRoutes);

router.use("/", couponRoutes);
router.use("/checkout-orders", checkoutOrderRoutes);
router.use("/coursejobs", coursejobRoutes);
router.use("/lesson-notes", lessonNoteRoutes);
router.use("/batches", batchRoutes); // ADD THIS

// Every entry in resourceMap.json (generated by scripts/generate-crud-resources.js) becomes
// /api/v1/<path> -> GET, GET/:id, POST, PUT/:id, DELETE/:id
resourceMap.forEach(({ path: resourcePath, file }) => {
  router.use(`/${resourcePath}`, require(`./${file}`));
});

module.exports = router;